Repository Grow-Fit/GrowFit-BE, pull requests merged in 2025-03, with the labels that each got.

#2 프로젝트 초기 설정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ Setting

#3 API 공통 응답 포맷 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/project/growfit/TestController.java
  src/main/java/com/project/growfit/global/exception/BusinessException.java
  src/main/java/com/project/growfit/global/exception/ErrorCode.java
  src/main/java/com/project/growfit/global/exception/GlobalExceptionHandler.java
  src/main/java/com/project/growfit/global/response/ErrorResponse.java
  src/main/java/com/project/growfit/global/response/ResultCode.java
  src/main/java/com/project/growfit/global/response/ResultResponse.java
  src/test/java/com/project/growfit/global/response/ErrorResponseTest.java
  src/test/java/com/project/growfit/global/response/ResultResponseTest.java
Labels: :memo: Docs, :sparkles: Feature, ✅ Test

#6 엔티티 구성 및 연관관계 설정
  src/main/java/com/project/growfit/domain/Board/entity/Bookmark.java
  src/main/java/com/project/growfit/domain/Board/entity/Category.java
  src/main/java/com/project/growfit/domain/Board/entity/Comment.java
  src/main/java/com/project/growfit/domain/Board/entity/Image.java
  src/main/java/com/project/growfit/domain/Board/entity/Like.java
  src/main/java/com/project/growfit/domain/Board/entity/Post.java
  src/main/java/com/project/growfit/domain/Diet/entity/Diet.java
  src/main/java/com/project/growfit/domain/Diet/entity/Food.java
  src/main/java/com/project/growfit/domain/Diet/entity/MealType.java
  src/main/java/com/project/growfit/domain/Diet/entity/Sticker.java
  src/main/java/com/project/growfit/domain/Goal/entity/CertType.java
  src/main/java/com/project/growfit/domain/Goal/entity/Goal.java
  src/main/java/com/project/growfit/domain/Goal/entity/GoalAcc.java
  src/main/java/com/project/growfit/domain/Goal/entity/GoalBoard.java
  src/main/java/com/project/growfit/domain/Goal/entity/GoalCertDays.java
  src/main/java/com/project/growfit/domain/Goal/entity/GoalProgress.java
  src/main/java/com/project/growfit/domain/Goal/entity/GoalState.java
  src/main/java/com/project/growfit/domain/Goal/entity/GoalType.java
  src/main/java/com/project/growfit/domain/Goal/entity/PeriodType.java
  src/main/java/com/project/growfit/domain/Goal/entity/RecommendGoal.java
  src/main/java/com/project/growfit/domain/Goal/entity/SuccessStatus.java
  src/main/java/com/project/growfit/domain/User/entity/AnalysisType.java
  src/main/java/com/project/growfit/domain/User/entity/BmiAnalysis.java
  src/main/java/com/project/growfit/domain/User/entity/CharacterType.java
  src/main/java/com/project/growfit/domain/User/entity/Child.java
  src/main/java/com/project/growfit/domain/User/entity/ChildBodyInfo.java
  src/main/java/com/project/growfit/domain/User/entity/ChildCharacter.java
  src/main/java/com/project/growfit/domain/User/entity/ChildGender.java
  src/main/java/com/project/growfit/domain/User/entity/Feedback.java
  src/main/java/com/project/growfit/domain/User/entity/Parent.java
  src/main/java/com/project/growfit/global/entity/BaseEntity.java
Labels: ⚙️ Setting, :sparkles: Feature

#8 회원가입 및 로그인 기능 구현
  build.gradle
  src/main/java/com/project/growfit/GrowfitApplication.java
  src/main/java/com/project/growfit/domain/Board/entity/Like.java
  src/main/java/com/project/growfit/domain/User/controller/AuthChildController.java
  src/main/java/com/project/growfit/domain/User/controller/AuthParentController.java
  src/main/java/com/project/growfit/domain/User/controller/OAuthController.java
  src/main/java/com/project/growfit/domain/User/controller/PageController.java
  src/main/java/com/project/growfit/domain/User/dto/request/ChildCredentialsRequest.java
  src/main/java/com/project/growfit/domain/User/dto/request/FindChildPasswordRequestDto.java
  src/main/java/com/project/growfit/domain/User/dto/request/ParentSignUpRequest.java
  src/main/java/com/project/growfit/domain/User/dto/request/RegisterChildRequest.java
  src/main/java/com/project/growfit/domain/User/dto/request/UpdateNicknameRequestDto.java
  src/main/java/com/project/growfit/domain/User/dto/request/UpdateNotificationRequestDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ChildBodyInfoResponseDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ChildInfoResponseDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ChildQrCodeResponseDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ParentLoginResponseDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ParentResponse.java
  src/main/java/com/project/growfit/domain/User/entity/Child.java
  src/main/java/com/project/growfit/domain/User/entity/ChildBodyInfo.java
  src/main/java/com/project/growfit/domain/User/entity/ChildGender.java
  src/main/java/com/project/growfit/domain/User/entity/Parent.java
  src/main/java/com/project/growfit/domain/User/entity/ROLE.java
  src/main/java/com/project/growfit/domain/User/repository/ChildRepository.java
  src/main/java/com/project/growfit/domain/User/repository/ParentRepository.java
  src/main/java/com/project/growfit/domain/User/service/AuthChildService.java
  src/main/java/com/project/growfit/domain/User/service/AuthParentService.java
  src/main/java/com/project/growfit/domain/User/service/OauthService.java
  src/main/java/com/project/growfit/domain/User/service/impl/AuthChildServiceImpl.java
  src/main/java/com/project/growfit/domain/User/service/impl/AuthParentServiceImpl.java
  src/main/java/com/project/growfit/domain/User/service/impl/OauthServiceImpl.java
  src/main/java/com/project/growfit/global/auto/dto/CustomUserDetails.java
  src/main/java/com/project/growfit/global/auto/filter/JwtCookieAuthenticationFilter.java
  src/main/java/com/project/growfit/global/auto/filter/LoginFilter.java
  src/main/java/com/project/growfit/global/auto/jwt/JwtProvider.java
  src/main/java/com/project/growfit/global/auto/jwt/excpetion/CustomAccessDeniedHandler.java
  src/main/java/com/project/growfit/global/auto/jwt/excpetion/CustomAuthenticationEntryPoint.java
  src/main/java/com/project/growfit/global/auto/jwt/excpetion/EntryPointErrorResponse.java
  src/main/java/com/project/growfit/global/auto/service/CustomAuthenticationProvider.java
  src/main/java/com/project/growfit/global/auto/service/CustomUserDetailsService.java
  src/main/java/com/project/growfit/global/config/RedisRepositoryConfig.java
  src/main/java/com/project/growfit/global/config/SecurityConfig.java
  src/main/java/com/project/growfit/global/entity/BaseEntity.java
  src/main/java/com/project/growfit/global/exception/ErrorCode.java
  src/main/java/com/project/growfit/global/redis/entity/TokenRedis.java
  src/main/java/com/project/growfit/global/redis/repository/TokenRedisRepository.java
  src/main/java/com/project/growfit/global/response/ResultCode.java
  src/main/java/com/project/growfit/global/utils/CookieUtils.java
  src/test/java/com/project/growfit/domain/auth/controller/AuthChildControllerTest.java
  src/test/java/com/project/growfit/domain/auth/controller/AuthParentControllerTest.java
  src/test/java/com/project/growfit/domain/auth/controller/OAuthControllerTest.java
  src/test/java/com/project/growfit/domain/auth/repository/ChildRepositoryTest.java
  src/test/java/com/project/growfit/domain/auth/repository/ParentRepositoryTest.java
  src/test/java/com/project/growfit/domain/auth/service/impl/AuthChildServiceImplTest.java
  src/test/java/com/project/growfit/domain/auth/service/impl/AuthParentServiceImplTest.java
Labels: :sparkles: Feature

#10 feat: Swagger 설정 클래스 추가
  src/main/java/com/project/growfit/domain/User/controller/TestPageController.java
  src/main/java/com/project/growfit/global/config/SwaggerConfig.java
Labels: ⚙️ Setting, :sparkles: Feature
