Repository Grow-Fit/GrowFit-BE, pull requests merged in 2025-06, with the labels that each got.

#28 식단 데이터타입 및 영양소 계산 오류 수정
  src/main/java/com/project/growfit/domain/Diet/controller/DietController.java
  src/main/java/com/project/growfit/domain/Diet/dto/request/FoodItemDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/DailyDietResponseDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/DietDetailResponseDto.java
  src/main/java/com/project/growfit/domain/Diet/entity/DailyDiet.java
  src/main/java/com/project/growfit/domain/Diet/entity/Diet.java
  src/main/java/com/project/growfit/domain/Diet/entity/DietSetFood.java
  src/main/java/com/project/growfit/domain/Diet/entity/DietState.java
  src/main/java/com/project/growfit/domain/Diet/service/DietService.java
  src/main/java/com/project/growfit/domain/Diet/service/impl/DietServiceImpl.java
  src/main/java/com/project/growfit/domain/Diet/service/impl/DietSetServiceImpl.java
  src/main/java/com/project/growfit/domain/User/controller/AuthParentController.java
  src/main/java/com/project/growfit/domain/User/controller/TestAuthController.java
  src/main/java/com/project/growfit/domain/User/service/AuthParentService.java
  src/main/java/com/project/growfit/domain/User/service/impl/AuthChildServiceImpl.java
  src/main/java/com/project/growfit/domain/User/service/impl/AuthParentServiceImpl.java
  src/main/java/com/project/growfit/domain/User/service/impl/OauthServiceImpl.java
  src/main/java/com/project/growfit/domain/board/service/CommentService.java
  src/main/java/com/project/growfit/domain/board/service/PostService.java
  src/main/java/com/project/growfit/domain/board/service/RedisPostService.java
  src/main/java/com/project/growfit/domain/board/service/UserPostService.java
  src/main/java/com/project/growfit/global/auth/dto/CustomUserDetails.java
  src/main/java/com/project/growfit/global/auth/filter/JwtCookieAuthenticationFilter.java
  src/main/java/com/project/growfit/global/auth/filter/LoginFilter.java
  src/main/java/com/project/growfit/global/auth/jwt/JwtProvider.java
  src/main/java/com/project/growfit/global/auth/jwt/excpetion/CustomAccessDeniedHandler.java
  src/main/java/com/project/growfit/global/auth/jwt/excpetion/CustomAuthenticationEntryPoint.java
  src/main/java/com/project/growfit/global/auth/jwt/excpetion/EntryPointErrorResponse.java
  src/main/java/com/project/growfit/global/auth/service/AuthenticatedUserProvider.java
  src/main/java/com/project/growfit/global/auth/service/CustomAuthenticationProvider.java
  src/main/java/com/project/growfit/global/auth/service/CustomUserDetailsService.java
  src/main/java/com/project/growfit/global/config/SecurityConfig.java
  src/test/java/com/project/growfit/domain/User/controller/AuthParentControllerTest.java
  src/test/java/com/project/growfit/domain/User/service/impl/AuthChildServiceImplTest.java
  src/test/java/com/project/growfit/domain/User/service/impl/AuthParentServiceImplTest.java
  src/test/java/com/project/growfit/domain/auth/controller/AuthChildControllerTest.java
  src/test/java/com/project/growfit/domain/auth/controller/AuthParentControllerTest.java
Labels: :bug: Bug, 🎨 Fix

#30 식단 미이행 대응 로직 개선 및 리팩토링
  src/main/java/com/project/growfit/domain/Diet/controller/DietController.java
  src/main/java/com/project/growfit/domain/Diet/dto/request/UpdateFoodListRequestDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/request/UpdateNutritionRequestDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/DietDetailResponseDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/DietResponseDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/FoodResponseDto.java
  src/main/java/com/project/growfit/domain/Diet/entity/Diet.java
  src/main/java/com/project/growfit/domain/Diet/service/DietService.java
  src/main/java/com/project/growfit/domain/Diet/service/impl/DietServiceImpl.java
  src/main/java/com/project/growfit/domain/Diet/service/impl/DietSetServiceImpl.java
  src/main/java/com/project/growfit/global/response/ResultCode.java
Labels: :hammer: Refactor, :sparkles: Feature

#32 import 경로 수정하여 cicd 문제 해결
  src/main/java/com/project/growfit/domain/notice/controller/SseController.java
  src/main/java/com/project/growfit/domain/notice/service/impl/NoticeServiceImpl.java
  src/main/java/com/project/growfit/domain/notice/service/impl/SseEmitterServiceImpl.java
  src/test/java/com/project/growfit/domain/notice/service/NoticeServiceTest.java
Labels: :bug: Bug

#48 리다이렉트 url 수정 및 환경변수로 설정
  src/main/java/com/project/growfit/domain/User/controller/OAuthController.java
Labels: :bug: Bug, 🎨 Fix

#50 Refactor/46 common api response
  build.gradle
  src/main/java/com/project/growfit/domain/Diet/controller/DietController.java
  src/main/java/com/project/growfit/domain/Diet/controller/DietSetController.java
  src/main/java/com/project/growfit/domain/Diet/dto/request/UpdateDietRequestDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/DietBasicDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/DietSetBasicDto.java
  src/main/java/com/project/growfit/domain/Diet/dto/response/MonthlyStickerResponseDto.java
  src/main/java/com/project/growfit/domain/Diet/entity/Diet.java
  src/main/java/com/project/growfit/domain/Diet/service/DietService.java
  src/main/java/com/project/growfit/domain/Diet/service/DietSetService.java
  src/main/java/com/project/growfit/domain/Diet/service/impl/DietServiceImpl.java
  src/main/java/com/project/growfit/domain/Diet/service/impl/DietSetServiceImpl.java
  src/main/java/com/project/growfit/domain/User/controller/AuthChildController.java
  src/main/java/com/project/growfit/domain/User/controller/AuthParentController.java
  src/main/java/com/project/growfit/domain/User/controller/OAuthController.java
  src/main/java/com/project/growfit/domain/User/dto/request/AuthChildRequestDto.java
  src/main/java/com/project/growfit/domain/User/dto/request/FindChildPasswordRequestDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ChildBodyInfoResponseDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ChildIdResponse.java
  src/main/java/com/project/growfit/domain/User/dto/response/ChildInfoResponseDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ChildResponseDto.java
  src/main/java/com/project/growfit/domain/User/dto/response/ParentResponseDto.java
  src/main/java/com/project/growfit/domain/User/repository/ChildRepository.java
  src/main/java/com/project/growfit/domain/User/service/AuthChildService.java
  src/main/java/com/project/growfit/domain/User/service/AuthParentService.java
  src/main/java/com/project/growfit/domain/User/service/OauthService.java
  src/main/java/com/project/growfit/domain/User/service/impl/AuthChildServiceImpl.java
  src/main/java/com/project/growfit/domain/User/service/impl/AuthParentServiceImpl.java
  src/main/java/com/project/growfit/domain/User/service/impl/OauthServiceImpl.java
  src/main/java/com/project/growfit/global/auth/jwt/JwtProvider.java
  src/main/java/com/project/growfit/global/auth/service/AuthenticatedUserProvider.java
  src/main/java/com/project/growfit/global/exception/ErrorCode.java
  src/main/java/com/project/growfit/global/response/ResultCode.java
  src/test/java/com/project/growfit/domain/Diet/service/impl/DietServiceImplTest.java
  src/test/java/com/project/growfit/domain/Diet/service/impl/DietSetServiceImplTest.java
  src/test/java/com/project/growfit/domain/User/repository/ChildRepositoryTest.java
  src/test/java/com/project/growfit/domain/User/service/impl/AuthChildServiceImplTest.java
  src/test/java/com/project/growfit/domain/User/service/impl/AuthParentServiceImplTest.java
  src/test/java/com/project/growfit/domain/User/service/impl/OauthServiceImplTest.java
Labels: :hammer: Refactor, :sparkles: Feature
